[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
bsc_mainnet = "https://bsc-dataseed.binance.org/"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

[etherscan]
bsc_mainnet = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
